baseURL = "https://jinojose.in"
title = "Jinos Blog"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; 2018, Jino Jose"

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/projects/index.html"
    weight = -90

# Configuration Features
[params]
  description = "Jinos Blog"
  header_title = "Jino Jose"                
  header_subtitle = "Golang | DevOps |  AI/ML" 
  home_image = "/images/jino.jpg"          
  recent_posts = 1                        
  mainSections = ["posts", "post", "Blogs"]   
  [params.style]                           
    backgroundColor = "#f8f9fa"
    homeImageBorderColor = "#ffffff"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#212529"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/JinoArch"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "https://www.linkedin.com/in/jino-jose-296928198"
