baseURL: https://jinoarch.github.io/tech-repo
languageCode: en-us
defaultContentLanguage: en
title: Jinos Blog
theme: cupper-hugo-theme

params:
  description: DevOps Engineer And Python Programmer
  homeMetaContent: DevOps And Python Programmer
  footer: Rolling Release + Maintained By Jino Jose
  dateFormat: Oct 8, 2020
  katex: true
  darkThemeAsDefault: false
  hideHeaderLinks: false
  search: true


menu:
  nav:
    - name: Blog
      url: https://jinojose.online/blogs/
      weight: 1
    - name: Offtopics
      url: https://jinojose.online/offtopics/
      weight: 2
    - name: WhoAmI
      url: https://jinojose.online/whoami/
      weight: 3


markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
